@host = http://localhost:5000/api

#### create random users
POST {{host}}/faker
Content-Type: application/json


#### update schema
POST {{host}}/migration
Content-Type: application/json

{
  "caste": "Balija - Gavara Naidu",
  "to": "Naidu",
  "subTo": "Balija"
}


#### get static files
GET {{host}}/static/v1/castes.json
